config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  root :to => "home#index"
  resources :rooms do
    resources :messages, only: [:create, :destroy]
  end

  get "/search", to: "search#index"

  resources :profiles, only: [:show]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def find_users_rooms user
        user_rooms = []
        UserToRoom.where(user_id: user.id).each { |room| user_rooms << room.room_id }
        return user_rooms
    end

    def show
        @user = User.find(params[:id])
        
        current_user_rooms = find_users_rooms(current_user)
        user_rooms = find_users_rooms(@user)

        common_rooms_id = current_user_rooms & user_rooms
        @privat_room = Room.where(id: common_rooms_id, room_status: 0)[0]

        @common_rooms = Room.where(id: common_rooms_id, room_status: 1)
        @conv_rooms = Room.where(id: current_user_rooms, room_status: 1).where.not(id: common_rooms_id)
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_links_to_rooms.html.erb
<div class="row mb-3">
    <div class="col">
        <% if @privat_room.present? %>
        <div class="d-grid grap-2">
            <%= link_to "Отправить личиное сообщение", room_path(@privat_room), data: {turbo: false}, class: "btn btn-primary" %>
        </div>
        <% else %>
            <%= form_tag rooms_url, method: :post do %>
                <%= hidden_field_tag "user_id", @user.id %>
                <%= hidden_field_tag "room_status", 0 %>
            <div class="d-grid grap-2">
                <%= submit_tag "Отправить личиное сообщение", data: {turbo: false}, class: "btn btn-primary" %>
            </div>
            <% end %>
        <% end %>
    </div>
</div>
<div class="row mb-3">
    <div class="col">
        <div class="d-grid grap-2 mb-2">
            <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#invite_to_room" aria-expanded="false">Пригласить в беседу</button>
        </div>
        <div class="collapse mb-2" id="invite_to_room">
            <div class="card card-body">
                <%= form_tag rooms_url, method: :post do %>
                    <%= hidden_field_tag "user_id", @user.id %>
                    <%= hidden_field_tag "room_status", 1 %>
                <div class="d-grid grap-2 mb-3">
                    <%= submit_tag "Создать новую беседу", data: {turbo: false}, class: "btn btn-primary" %>
                </div>
                <% end %>
                <ul class="list-group list-group-flush">
                    <% if @common_rooms.present? %>
                        <p class="fs-5 lh-1" style="text-align: center">Продолжить общение</p>
                        <% @common_rooms.each do |room| %>
                            <%= link_to render(partial: "room_item", collection: @common_rooms, as: :room), room_path(room), class: " list-group-item list-group-item-action" %>  
                        <% end %>
                    <% end %>
                    <% if @conv_rooms.present? %>
                        <p class="fs-5 lh-1" style="text-align: center">Пригласить в беседу</p>
                        <% @conv_rooms.each do |room| %>
                            <%= button_to render(partial: "room_item", collection: @conv_rooms, as: :room), rooms_url(room_status: 2, room_id: room.id, user_id: @user.id), method: :post, data: {turbo: false}, style: "border-left: none; border-right: none; border-top: none", class: "list-group-item list-group-item-action" %>
                        <% end %>
                    <% else %>
                        <li class="list-group-item" style="text-align: center">Нет бесед для приглашения</li>
                    <% end %>
                </ul>
            </div>
          </div>
    </div>
</div>

app/views/profiles/_room_item.html.erb
<div class="row">
    <div class="col-auto ps-0 pe-0">
        <% if room.image.present? %>
        <% else %>
            <%= image_tag("default_message_icon.png", size: "60x60", class: "user-avarat-style") %>
        <% end %>
    </div>
    <div class="col">
        <div class="row">
            <div class="col">
                <p class="fw-semibold lh-1"><%= room.name %></p>
            </div>
            <div class="col-auto align-self-end">
                <p class="fs-6 lh-1"><%= room.updated_at.to_time.strftime("%d.%m.%Y %H:%M") %></p>
            </div>
        </div>
        <div class="row">
            <p class="lh-1"><%= room.last_message %></p>
        </div>
    </div>
</div>

app/views/profiles/show.html.erb
<div class="row justify-content-md-center">
    <div class="col-xxl-4 col-xl-6 col-md-6 col">
        <div class="row mb-3">
            <div class="col-auto">
                <% if @user.avatar.present? %>
                    <%= image_tag(@user.avatar.variant(resize_to_fill: [200, 200]), class: "user-avarat-style") %>
                <% else %>
                    <%= image_tag("default_user_avatar.png", size: "200x200", class: "user-avarat-style") %>
                <% end %>
            </div>
            <div class="col flex-column align-self-center">
                <h2 class="fw-normal"><%= @user.username %></h2>
                <h5 class="fw-light"><%= @user.birthday.present? ? @user.birthday.to_time.strftime("%d.%m.%Y") : "" %></h5>
                <h5 class="fw-light"><%= @user.country.present? ? @user.country + ", ": "" %><%= @user.city %></h5>
                <% if current_user.id == @user.id %>
                    <%= link_to 'Редактировать профиль', edit_user_registration_path, data: {turbo: false}, style: "text-decoration: none" %>
                <% end %>
            </div>
        </div>
        <% unless current_user.id == @user.id %>
            <%= render "links_to_rooms" %>
        <% end %>
    </div>
</div>