config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}

  root :to => "home#index"
  resources :rooms do
    resources :messages, only: [:create, :destroy]
  end

  get "/search", to: "search#index"

  resources :profiles, only: [:show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_guest_home_page.html.erb
<div class="container-fluid height-80">
    <div class="row justify-content-md-center height-80">
        <div class="col-xxl-4 col-xl-6 col-md-6 col align-self-center">
            <div style="text-align: center">
                <div class="mb-3">
                    <%= image_tag ("messanger_logo.png"), class: "img-fluid" %>
                </div>
                <p class="fs-1">Добро пожаловать</p>
                <div class="row">
                    <div class="col">
                        <div class="d-grid grap-2 mb-3">
                            <%= link_to "Войти", new_user_session_url, data: {turbo: false}, class: "btn btn-primary" %>
                        </div>
                    </div>
                    <div class="col">
                        <div class="d-grid grap-2 mb-3">
                            <%= link_to "Регистрация", new_user_registration_url, data: {turbo: false}, class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/_user_home_page.html.erb
<div class="container-fluid height-80">
    <div class="row justify-content-md-center height-80">
        <div class="col-xxl-4 col-xl-6 col-md-6 col align-self-center">
            <div style="text-align: center">
                <div class="mb-3">
                    <% if current_user.avatar.present? %>
                        <%= image_tag(current_user.avatar.variant(resize_to_fill: [250, 250]), class: "user-avarat-style") %>
                    <% else %>
                        <%= image_tag("default_user_avatar.png", size: "250x250", class: "user-avarat-style") %>
                    <% end %>
                </div>
                <p class="fs-1"><%= current_user.username %></p>
                <div class="row">
                    <div class="col">
                        <div class="d-grid grap-2 mb-3">
                            <%= link_to "Найти пользователя", search_url, data: {turbo: false}, class: "btn btn-primary mb-3" %>
                            <%= link_to "Перейти к сообщениям", rooms_url, data: {turbo: false}, class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="d-grid grap-2 mb-3">
                            <%= link_to "Профиль", profile_path(current_user.id), data: {turbo: false}, class: "btn btn-primary" %>
                        </div>
                    </div>
                    <div class="col">
                        <div class="d-grid grap-2 mb-3">
                            <%= link_to "Выйти", destroy_user_session_url, data: {turbo_method: :delete}, class: "btn btn-danger" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div>
    <% if current_user.present? %>
        <%= render "user_home_page" %>
    <% else %>
        <%= render "guest_home_page" %>
    <% end %>
</div>